{{- if .Values.workerSchedulerEnabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker-scheduler
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        stage: {{ .Values.stage }}
        tier: worker-scheduler
    spec:
      containers:
      - name: {{ .Chart.Name }}-worker-scheduler
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        command: ["celery", "beat", "--app=celery_worker.celery"]
        env:
        - name: DB_HOST
          value: {{ template "fullname" . }}-db
        - name: DB_PORT
          value: {{ .Values.dbPort | quote }}
        - name: DB_USERNAME
          value: {{ .Values.dbUsername }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql_password
        - name: DB_NAME
          value: {{ .Values.dbName }}
        - name: CELERY_BROKER_URL
          value: "redis://{{ template "fullname" . }}-redis:{{ .Values.redis.service.port }}"
        - name: CAS_SERVER
          value: {{ .Values.casServer }}
        - name: CAS_AUTH_PREFIX
          value: {{ .Values.casAuthPrefix }}
        - name: XAPI_ENABLED
          value: {{ .Values.xapiEnabled | quote }}
        - name: XAPI_APP_BASE_URL
          value: {{ .Values.xapiAppBaseURL }}
        - name: LRS_STATEMENT_ENDPOINT
          value: {{ .Values.lrsStatementEndpoint }}
        - name: LRS_USERNAME
          value: {{ .Values.lrsUsername }}
        - name: LRS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: lrs_password
        - name: LRS_ACTOR_ACCOUNT_USE_CAS
          value: {{ .Values.lrsActorAccountUseCas | quote }}
        - name: LRS_ACTOR_ACCOUNT_CAS_IDENTIFIER
          value: {{ .Values.lrsActorAccountCasIdentifier }}
        - name: LRS_ACTOR_ACCOUNT_CAS_HOMEPAGE
          value: {{ .Values.lrsActorAccountCasHomepage }}
        - name: ASSET_LOCATION
          value: {{ .Values.assetLocation }}
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: secret_key
        - name: C_FORCE_ROOT
          value: {{ .Values.cForceRoot | quote }}
        - name: ENFORCE_SSL
          value: {{ .Values.enforceSSL | quote }}
        - name: DEMO_INSTALLATION
          value: {{ .Values.demoInstance | quote }}
        - name: CELERY_TIMEZONE
          value: {{ .Values.celeryTimezone | quote }}
{{- end }}
