apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.CI_PIPELINE_ID }}
    autodeployed: "true"
    pipeline_id: "{{  .Values.CI_PIPELINE_ID }}"
    {{- end }}
    {{- if .Values.CI_BUILD_ID }}
    build_id: "{{ .Values.CI_BUILD_ID }}"
    {{- end }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        stage: {{ .Values.stage }}
        tier: worker
    spec:
      containers:
      - name: {{ .Chart.Name }}-worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        command: ["celery", "worker", "--app=celery_worker.celery", "--loglevel=INFO"]
        env:
        - name: DB_HOST
          value: {{ template "fullname" . }}-db
        - name: DB_PORT
          value: {{ .Values.dbPort }}
        - name: DB_USERNAME
          value: {{ .Values.dbUsername }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql_password
        - name: DB_NAME
          value: {{ .Values.dbName }}
        - name: CELERY_BROKER_URL
          value: "redis://{{ template "fullname" . }}-redis:{{ .Values.redis.service.port }}"
        - name: ATTACHMENT_UPLOAD_LIMIT
          value: {{ .Values.attachmentUploadLimit | quote }}
        - name: APP_LOGIN_ENABLED
          value: {{ .Values.appLoginEnabled | quote }}
        - name: CAS_ENABLED
          value: {{ .Values.cas.enabled | quote }}
        {{- if .Values.cas.enabled }}
        - name: CAS_SERVER
          value: {{ .Values.cas.server }}
        - name: CAS_AUTH_PREFIX
          value: {{ .Values.cas.authPrefix }}
        - name: CAS_USE_SAML
          value: {{ .Values.cas.useSAML | quote }}
        {{- end }}
        - name: XAPI_ENABLED
          value: {{ .Values.xapi.enabled | quote }}
        {{- if .Values.xapi.enabled }}
        - name: XAPI_APP_BASE_URL
          value: {{ .Values.xapi.appBaseURL }}
        - name: LRS_STATEMENT_ENDPOINT
          value: {{ .Values.xapi.lrsStatementEndpoint }}
        - name: LRS_USERNAME
          value: {{ .Values.xapi.lrsUsername }}
        - name: LRS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: lrs_password
        - name: LRS_ACTOR_ACCOUNT_USE_CAS
          value: {{ .Values.xapi.lrsActorAccountUseCas | quote }}
        - name: LRS_ACTOR_ACCOUNT_CAS_IDENTIFIER
          value: {{ .Values.xapi.lrsActorAccountCasIdentifier }}
        - name: LRS_ACTOR_ACCOUNT_CAS_HOMEPAGE
          value: {{ .Values.xapi.lrsActorAccountCasHomepage }}
        {{- end }}
        - name: ASSET_LOCATION
          value: {{ .Values.assetLocation }}
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: secret_key
        - name: C_FORCE_ROOT
          value: {{ .Values.cForceRoot | quote }}
        - name: ENFORCE_SSL
          value: {{ .Values.enforceSSL | quote }}
        - name: DEMO_INSTALLATION
          value: {{ .Values.demoInstance | quote }}
        - name: CELERY_TIMEZONE
          value: {{ .Values.celeryTimezone | quote }}
        - name: MAIL_NOTIFICATION_ENABLED
          value: {{ .Values.mail.enabled | quote }}
        {{- if .Values.mail.enabled }}
        - name: MAIL_SERVER
          value: {{ .Values.mail.server }}
        - name: MAIL_PORT
          value: {{ .Values.mail.port | quote }}
        - name: MAIL_USE_SSL
          value: {{ .Values.mail.useSSL | quote }}
        - name: MAIL_USE_TLS
          value: {{ .Values.mail.useTLS | quote }}
        - name: MAIL_USERNAME
          value: {{ .Values.mail.username }}
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mail_password
        - name: MAIL_DEFAULT_SENDER
          value: {{ .Values.mail.defaultSender }}
        {{- end }}
        - name: KALTURA_ENABLED
          value: {{ .Values.kaltura.enabled | quote }}
        {{- if .Values.mail.enabled }}
        - name: KALTURA_SERVICE_URL
          value: {{ .Values.kaltura.serviceURL }}
        - name: KALTURA_PARTNER_ID
          value: {{ .Values.kaltura.partnerId | quote }}
        - name: KALTURA_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: kaltura_secret
        - name: MAIL_DEFAULT_SENDER
          value: {{ .Values.mail.defaultSender }}
        - name: KALTURA_USER_ID
          value: {{ .Values.kaltura.userId | quote }}
        - name: KALTURA_PLAYER_ID
          value: {{ .Values.kaltura.playerId | quote }}
        {{- end }}
      {{- if .Values.app.persistence.enabled }}
        volumeMounts:
        - name: {{ template "fullname" . }}-persistent-storage
          mountPath: /code/persistent
      volumes:
      - name: {{ template "fullname" . }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-app-pvc
      {{- end }}
