apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- include "common_labels" . | indent 4 }}
    tier: app
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}'
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: MEDIAWIKI_DB_HOST
          value: {{ template "db.fullname" . | default .Values.db.service.name }}
        - name: MEDIAWIKI_DB_PORT
          value: {{ .Values.db.service.port | quote }}
        - name: MEDIAWIKI_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: db_user
        - name: MEDIAWIKI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: db_password
        - name: MEDIAWIKI_DB_NAME
          value: {{ .Values.db.mysqlDatabase | quote }}
        - name: MEDIAWIKI_DB_SCHEMA
          value: {{ .Values.db.dbSchema | quote }}
        - name: MEDIAWIKI_ADMIN_USER
          value: {{ default "" .Values.adminUser | quote }}
        - name: MEDIAWIKI_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mediawiki_password
        - name: MEDIAWIKI_EMAIL
          value: {{ default "" .Values.mediawikiEmail | quote }}
        - name: MEDIAWIKI_SITE_SERVER
          value: https://{{ index .Values.ingress.hosts 0 | default .Values.CI_ENVIRONMENT_HOSTNAME | default "http://localhost" }}
        - name: MEDIAWIKI_SITE_NAME
          value: {{ .Values.mediawikiName | quote }}
        - name: MEDIAWIKI_SITE_LANG
          value: {{ .Values.mediawikiLang | quote }}
        - name: MEDIAWIKI_EXTENSIONS
          value: {{ .Values.mediawikiExts | quote }}
        - name: SMTP_HOST_ID
          value: {{ default "" .Values.smtpHostID | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: smtp_password
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.php/Main_Page
            port: http
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /index.php/Main_Page
            port: http
          initialDelaySeconds: 30
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: mediawiki-data
          mountPath: /data
      volumes:
      - name: mediawiki-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-app-pvc
      {{- else }}
        emptyDir: {}
      {{- end }}
