dependencies:
- name: mysql
  version: 0.2.6
  repository: https://kubernetes-charts.storage.googleapis.com/
  #  condition: db.mariadb
  alias: db
#- name: mariadb
#  version: 0.6.3
#  repository: https://kubernetes-charts.storage.googleapis.com/
#  #  condition: db.mariadb
#  alias: db
#- name: postgresql
#  version: 0.7.1
#  repository: https://kubernetes-charts.storage.googleapis.com/
#  condition: db.postgresql
#  alias: db
