## Bitnami MediaWiki image version
## ref: https://hub.docker.com/r/ubcctlt/mediawiki/tags/
##
image:
  repository: ubcctlt/mediawiki
  # tag: 

stage: dev
replicas: 1
## Specify a imagePullPolicy
## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## User of the application
##
adminUser: user

## Application password
## Defaults to a random 10-character alphanumeric string if not set
##
# adminPassword:

## Admin email
## ref: https://github.com/bitnami/bitnami-docker-mediawiki#environment-variables
##
mediawikiEmail: user@example.com

## Name for the wiki
##
mediawikiName: My Wiki

mediawikiLang: en

# Comma separated extension list
mediawikiExts: ""

## SMTP mail delivery configuration
## ref: https://github.com/bitnami/bitnami-docker-mediawiki#smtp-configuration
##
# smtpHost:
# smtpPort:
# smtpHostID:
# smtpUser:
# smtpPassword:

##
## MariaDB chart configuration
# ref: https://github.com/kubernetes/charts/tree/master/stable/mariadb
##
db:
  ## DB admin password
  ##
  #mariaRootPassword
  #mariadbUser: wiki
  #mariadbPassword:
  #mariaDatabase: mediawiki
  #
  #mysqlRootPassword:
  mysqlUser: wiki
  mysqlPassword: mediawiki
  mysqlDatabase: mediawiki

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: false
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 8Gi

  service:
    #name:
    port: 3306

service:
  name: mediawiki
  type: ClusterIP
  externalPort: 80
  internalPort: 80

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass: ""
  accessMode: ReadWriteMany
  size: 8Gi

ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    # if there are multiple host names, first one will be the primary.
    -
    #- wiki.example.local
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 300m
