{{- if .Values.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-app-pv
  labels:
    app: {{ template "fullname" . }}
    stage: {{ .Values.stage }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    tier: filestore
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
{{ toYaml .Values.persistence.resources | indent 2 }}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-app-pvc
  labels:
    app: {{ template "fullname" . }}
    stage: {{ .Values.stage }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    tier: filestore
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      stage: {{ .Values.stage }}
      tier: filestore
{{- end }}
