apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redirector.fullname" . }}
  labels:
    app: {{ template "redirector.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range .Values.redirect }}
  {{ .host }}.conf: |
    server {
      listen                *:80;
      server_name           {{ .host }};
      return 301 {{ .to }};

      root /var/www/html;
    }
{{- end -}}
